---
name: build

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17

      - shell: bash
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 make build OS_ARCH=linux_arm64 VERSION=0.0.0-testing
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build OS_ARCH=linux_amd64 VERSION=0.0.0-testing

      - uses: actions/upload-artifact@v3
        with:
          name: terraform-provider-prismacloudcompute
          path: terraform-provider-prismacloudcompute-*
